version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DOTNET_ENVIRONMENT=Production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
